Vagrant.configure("2") do |config|
  config.vm.define "Zabbix-S" do |subconfig|
    subconfig.vm.box = "sbeliakou/centos"
    subconfig.vm.hostname = "Zabbix-S"
    subconfig.vm.network :private_network, ip: "192.168.56.197"
    subconfig.vm.provision "shell", path: "Zabbix.sh"
    subconfig.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "Zabbix-S"
      end
  end
  
    config.vm.define "Zabbix-A" do |subconfig|
      subconfig.vm.box = "sbeliakou/centos"
      subconfig.vm.hostname = "Zabbix-A"
      subconfig.vm.network :private_network, ip: "192.168.56.198"
      subconfig.vm.provision "shell", path: "Zabbix.sh"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.name = "Zabbix-A"
        end
     end
  end



